AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # RDS作成
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: MyDB
      VPCSecurityGroups:
        - !ImportValue DBEC2SecurityGroup
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: test12345
      DBSubnetGroupName: !Ref DBSubnetGroup
      EnableIAMDatabaseAuthentication: true
      Tags:
        - Key: Name
          Value: CF-Tutorial

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: DB subnet group
      SubnetIds:
          - !ImportValue PrivateSubnet
          - !ImportValue PrivateSubnet2
      Tags:
        - Key: Name
          Value: CF-Tutorial
